[project]
site_name = "bibsync Documentation"
site_description = "Synchronize BibTeX files from LaTeX citation keys using NASA ADS and InspireHEP."
site_author = "Isaac C. F. Wong"
copyright = """
Copyright &copy; 2026 Isaac C. F. Wong
"""

nav = [
  { "Overview" = "index.md" },
  { "User Guide" = [
    { "Installation" = "user-guide/installation.md" },
    { "Usage" = "user-guide/usage.md" },
    { "Providers" = "user-guide/providers.md" },
    { "Pre-commit" = "user-guide/pre-commit.md" },
    { "Examples" = "user-guide/examples.md" },
  ] },
  { "API" = [
    { "Overview" = "api/index.md" },
  ] },
  { "Contributing" = "contributing.md" },
  { "Security" = "security.md" },
]

[project.theme]
language = "en"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.path",
  "navigation.sections",
  "search.highlight",
  "search.suggest",
  "toc.follow",
]

[repo]
url = "https://github.com/isaac-cf-wong/bibsync"
name = "bibsync"

[markdown_extensions]
admonition = {}
attr_list = {}
footnotes = {}
md_in_html = {}

[markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[markdown_extensions.pymdownx.superfences]

[plugins]
search = {}
